apiVersion: v1
kind: Service
metadata:
  name: go-svc
  labels:
    name: go-service
    app: go-svc-app
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8000
  selector:
    name: go-svc
    app: go-svc-app